[platformio]
default_envs = tab5

[env:tab5]
platform = espressif32
board = esp32-p4-evboard
framework = arduino

board_build.mcu = esp32p4
board_build.flash_mode = qio
upload_speed = 460800
monitor_speed = 115200

build_type = release
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    m5stack/M5Unified@0.2.14
    m5stack/M5GFX@0.2.21
