#include "GameContent.h"

// Item definitions are authored data. Runtime code equips or consumes them by
// reading ItemUseProfile, which keeps future item behavior extensible.
Item itemCatalog[] = {
    {"Patch Mask", "suit", Slot::Suit, ItemImageKind::PatchMask, 0, 0, 0, 0, 1, 0, 6, 110, 150, 150, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "You settle the mask straps until each breath sounds borrowed."},
     "A patched respirator and tarred hood. Bad fashion, good filters.",
     "Worn against weather, bad air, panic sweat, and whatever the rain is learning to become."},
    {"Rubber Trench", "suit", Slot::Suit, ItemImageKind::RubberTrench, 1, 0, 0, -1, 2, 0, 14, 90, 180, 120, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The trench coat seals with a rubber sigh and a smell of old cleanup crews."},
     "Heavy sealed coat from a cleanup crew that never came back.",
     "Heavy protection for hot rain and sharp debris. It keeps you alive, but not graceful."},
    {"Mirrorweave Coat", "suit", Slot::Suit, ItemImageKind::MirrorweaveCoat, 0, 1, 0, 2, 1, 0, 18, 190, 90, 210, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Mirrorweave threads take the light and give back someone less obvious."},
     "Chameleon threads shimmer under old advert light.",
     "A stealth coat with firmware in the fabric. Cameras dislike it. So do honest mirrors."},
    {"Coil Detector", "detector", Slot::Detector, ItemImageKind::CoilDetector, 0, 0, 1, 0, 0, 0, 8, 80, 200, 220, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The coil wakes with a dry click and begins listening under the pavement."},
     "Cheap copper loop detector. It screams before the world bends.",
     "Useful when the world lies visually. Crude, sturdy, and loud enough to keep you cautious."},
    {"Glass Needle", "detector", Slot::Detector, ItemImageKind::GlassNeedle, 0, 1, 3, 0, 0, 1, 20, 90, 230, 190, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The glass needle points somewhere your hand does not want to go."},
     "A precise anomaly pick. Every reading leaves a headache.",
     "Fine anomaly work at a cost. It finds the quiet impossibilities and leaves a little static behind your eyes."},
    {"Prybar Kit", "tool", Slot::Tool, ItemImageKind::PrybarKit, 1, 0, 0, 0, 0, 0, 7, 220, 180, 70, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "You roll the kit tight. The prybar knocks once against your boot."},
     "A prybar, pliers, tape and stubbornness in a cracked roll.",
     "Turns locked places into negotiations. Also turns quiet places into loud ones."},
    {"Solder Rig", "tool", Slot::Tool, ItemImageKind::SolderRig, 0, 3, 0, 0, 0, 0, 19, 230, 120, 70, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The solder rig warms against your palm and starts looking for ports."},
     "Battery iron, fiber patcher and black market firmware clips.",
     "For powered doors, dead drones, wet panels, and anything pretending to be offline."},
    {"Quiet Nailgun", "weapon", Slot::Weapon, ItemImageKind::QuietNailgun, 1, 0, 0, 2, 0, 0, 12, 210, 80, 160, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The nailgun settles under your coat, blunt and professionally quiet."},
     "Industrial nailer tuned for close work and low attention.",
     "A problem solver with a small sound. Good for threats, locks, and bad ideas."},
    {"Rail Pistol", "weapon", Slot::Weapon, ItemImageKind::RailPistol, 3, 0, 0, -1, 0, 1, 24, 230, 70, 90, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The rail pistol arms bright enough to make nearby shadows take a step back."},
     "Hard recoil, bright flash, very persuasive.",
     "A loud answer. It wins arguments and starts investigations."},
    {"Warm Battery", "artifact", Slot::Artifact, ItemImageKind::WarmBattery, 0, 2, 0, 0, 0, 2, 30, 240, 190, 80, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The battery warms when you lie to yourself about why you kept it."},
     "A dry cell that charges itself and warms when lied to.",
     "Not equipment exactly. More like a small rule from somewhere else, pretending to be power storage."},
    {"Mourning Lens", "artifact", Slot::Artifact, ItemImageKind::MourningLens, 0, 0, 3, 0, 0, 2, 34, 120, 150, 250, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The lens darkens the world and reveals the edges of old mistakes."},
     "Smoke-dark glass that shows paths people failed to take.",
     "It sharpens observation by showing absence. The strain is remembering what was never yours."},
    {"Null Charm", "artifact", Slot::Artifact, ItemImageKind::NullCharm, 0, 0, 0, 2, 1, 1, 28, 120, 230, 170, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The charm goes cold. For a moment, even your reflection loses interest."},
     "A cold trinket that makes cameras lose interest.",
     "Carried invisibility with a price tag written in missing minutes."},
    {"Iodine Ampoule", "dose", Slot::Consumable, ItemImageKind::IodineAmpoule, 0, 0, 0, 0, 0, 0, 5, 170, 230, 80, 0,
     {ItemUseKind::Consume, 0, -5, 0, true, "Use Dose", "The iodine burns all the way down. Exposure drops, hands stop shaking."},
     "Bitter anti-rad dose. You only taste pennies for an hour.",
     "Temporary mercy against accumulated dose. Useful before the shaking makes decisions for you."},
    {"Canned Coffee", "dose", Slot::Consumable, ItemImageKind::CannedCoffee, 0, 0, 0, 0, 0, 0, 4, 180, 120, 80, 0,
     {ItemUseKind::Consume, 2, 0, 0, true, "Drink", "Coffee syrup, cold and foul. You feel almost alive."},
     "Pre-collapse stimulant syrup. Technically food.",
     "A small bodily loan from a company that is probably still billing somebody."},
    {"Copper Saint", "artifact", Slot::Artifact, ItemImageKind::CopperSaint, 2, 0, 0, 0, 0, 2, 38, 210, 130, 60, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The little copper figure hums like a service tunnel full of prayers."},
     "A little idol that hums in broken service tunnels.",
     "A heavy charm of courage or foolishness. In the exclusion, those are often the same material."},
    {"Battery Cell", "trade", Slot::Consumable, ItemImageKind::WarmBattery, 0, 0, 0, 0, 0, 0, 3, 232, 190, 70, 0,
     {ItemUseKind::Consume, 0, 0, -1, true, "Burn",
      "You spend the cell on a dirty signal jammer. Nearby attention drops by one step."},
     "A taped industrial cell with enough charge to buy a meal, power a bypass, or silence a cheap alarm.",
     "Reliable barter because everyone needs power. Useful because power can still make things stop looking at you."},
    {"Clean Water", "trade", Slot::Consumable, ItemImageKind::CannedCoffee, 0, 0, 0, 0, 0, 0, 4, 95, 180, 220, 0,
     {ItemUseKind::Consume, 1, -1, 0, true, "Drink",
      "The water tastes faintly of charcoal and plastic. Body steadies, dose quiets."},
     "A sealed pouch of filtered water, stamped with a clinic checksum and a warning not to trust the seal.",
     "Common money in dry districts. Also exactly what your body keeps asking for."},
    {"Med Pack", "trade", Slot::Consumable, ItemImageKind::IodineAmpoule, 0, 0, 0, 0, 0, 0, 7, 216, 88, 96, 0,
     {ItemUseKind::Consume, 3, 0, 0, true, "Patch",
      "You spend the pack on clot foam and bitter tabs. Body recovers before pride does."},
     "Bandage rolls, clot foam, and two anonymous tablets in a waxed paper sleeve.",
     "High-value barter because pain is universal. Keeping it may matter more than spending it."},
    {"Reedskin Mantle", "suit", Slot::Suit, ItemImageKind::RubberTrench, 0, 0, 1, 1, 1, 1, 20, 64, 126, 96, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The reed mantle settles late, still remembering wind."},
     "A hooded mantle grown from black reeds, tarp fibre, and old funeral ribbon. It smells like wet cutlery.",
     "It remembers wind from somewhere that has no weather left."},
    {"Hospital Vinyl Apron", "suit", Slot::Suit, ItemImageKind::PatchMask, 0, 1, 0, -1, 2, 0, 12, 170, 212, 190, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The apron creaks with clinic names and old chemical scores."},
     "A sleeveless clinic apron, thick with chemical scoring and old marker names.",
     "The stains are arranged like a map of the places people were too late."},
    {"Static Bridal Veil", "suit", Slot::Suit, ItemImageKind::MirrorweaveCoat, 0, 0, 1, 2, 0, 1, 22, 218, 210, 236, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The veil crackles when the nearest camera tries to remember you."},
     "A torn veil of smart-fabric mesh that crackles when cameras sweep across it.",
     "It makes you look like someone a machine promised to remember."},
    {"Roadworker Husk", "suit", Slot::Suit, ItemImageKind::RubberTrench, 2, 0, 0, -2, 2, 0, 21, 222, 154, 64, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Foam seals bite shut. The reflective ribs stop pretending you are subtle."},
     "A faded municipal exoshell with reflective ribs and emergency foam seals.",
     "The safety tags are newer than the corpse that wore it."},
    {"Flood Choir Waders", "suit", Slot::Suit, ItemImageKind::RubberTrench, 1, 0, 0, -1, 2, 0, 16, 82, 148, 198, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The waders seal high and the little bells begin their drowned hymn."},
     "Chest-high waders with tiny prayer bells sewn into the straps.",
     "Every step sounds like a small church drowning politely."},
    {"Ashfall Poncho", "suit", Slot::Suit, ItemImageKind::RubberTrench, 0, 0, 1, 0, 2, 0, 15, 144, 150, 152, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The grey poncho slides into place and refuses to dry."},
     "A grey disposable poncho that never tears and never dries.",
     "The rain slides off it as if ashamed to touch you."},
    {"Glasshouse Smock", "suit", Slot::Suit, ItemImageKind::MirrorweaveCoat, -1, 1, 2, -1, 1, 0, 17, 92, 210, 136, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The smock shows you the weather, then lets the weather look back."},
     "A transparent smock reinforced with greenhouse wire and algae-dark seals.",
     "You see the weather through it. The weather sees you back."},
    {"Debt Collector's Coat", "suit", Slot::Suit, ItemImageKind::MirrorweaveCoat, 2, 1, 0, -1, 0, 1, 25, 34, 34, 38, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Receipt paper whispers in the lining. You look regrettably official."},
     "A heavy black coat lined with receipt paper and stitched threat letters.",
     "It fits like authority borrowed from a worse person."},
    {"Dead Pager", "detector", Slot::Detector, ItemImageKind::CoilDetector, 0, 1, 1, 0, 0, 1, 13, 110, 185, 220, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The pager buzzes for an appointment nobody alive can keep."},
     "A cracked pager that receives messages from closed services and numbers nobody owns.",
     "It vibrates for appointments kept by the dead."},
    {"Moth Compass", "detector", Slot::Detector, ItemImageKind::CoilDetector, 0, 0, 2, 0, 0, 1, 18, 206, 188, 116, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The pinned moth twitches toward whatever the city is digesting."},
     "A synthetic moth pinned inside a brass compass. Its wings twitch toward profitable rot.",
     "The moth wants what the city is digesting."},
    {"Rain Counter", "detector", Slot::Detector, ItemImageKind::CoilDetector, 0, 1, 1, 0, 1, 0, 11, 86, 170, 214, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The counter clicks once for rain, twice for regret."},
     "A handheld clicker that counts raindrops that should have missed you.",
     "It clicks once for rain, twice for regret."},
    {"Kindling Scope", "detector", Slot::Detector, ItemImageKind::GlassNeedle, 0, 0, 2, 1, 0, 1, 17, 226, 116, 70, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Warm things bloom in the scope as tiny city fires."},
     "A stubby thermal scope that shows warm things as tiny city fires.",
     "Every living thing looks like evidence."},
    {"Bone Tuning Fork", "detector", Slot::Detector, ItemImageKind::GlassNeedle, 0, 0, 3, 0, 0, 2, 23, 226, 226, 202, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The fork hums a note between alive and affordable."},
     "A tuning fork carved from something too pale and too resonant.",
     "It sings the note between alive and affordable."},
    {"Checkout Oracle", "detector", Slot::Detector, ItemImageKind::CoilDetector, 0, 2, 1, 0, 0, 1, 16, 110, 210, 118, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The scanner wakes and prices the next thing before it is found."},
     "A barcode scanner with a cracked display that prices things not yet found.",
     "It knows the value of things before they admit being lost."},
    {"Sparrow Drone Shell", "detector", Slot::Detector, ItemImageKind::CoilDetector, 0, 2, 1, 1, 0, 0, 18, 138, 166, 178, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The wingless shell blinks one eye and remembers sky."},
     "A palm-sized drone husk with one working eye and no wings.",
     "It cannot fly, but it still remembers sky."},
    {"Glass Lung Meter", "detector", Slot::Detector, ItemImageKind::GlassNeedle, 0, 0, 2, 0, 2, 0, 15, 176, 228, 210, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Your breath leaves little weather reports inside the glass."},
     "A blown-glass bulb that clouds in the presence of bad air, lies, or ghosts.",
     "Your breath leaves little weather reports inside it."},
    {"Rain Key", "tool", Slot::Tool, ItemImageKind::SolderRig, 0, 3, 0, 1, 0, 1, 26, 94, 182, 214, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Wet teeth shift in the ceramic blank whenever you look away."},
     "A ceramic key blank with wet teeth that change while you are not looking.",
     "It fits locks that have not been built yet."},
    {"Drowned Register", "tool", Slot::Tool, ItemImageKind::SolderRig, 1, 2, 0, -1, 1, 1, 20, 88, 132, 172, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The register drawer sloshes and demands that every find be rung up."},
     "A shop till with a hand crank, prayer stickers, and a drawer full of black water.",
     "Every number rings up as a debt."},
    {"Service Worm", "tool", Slot::Tool, ItemImageKind::SolderRig, 0, 3, 1, 0, 0, 1, 19, 170, 116, 82, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The cable probe flexes. Its tiny head bites twice at the air."},
     "A flexible cable probe with a tiny biting maintenance head.",
     "It has no eyes, but it knows which walls are nervous."},
    {"Tar Tape Roll", "tool", Slot::Tool, ItemImageKind::PrybarKit, 0, 1, 0, -1, 2, 0, 9, 38, 42, 42, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Black tape sticks to your glove and several small mistakes."},
     "A roll of black adhesive tape that seals leaks, mouths, and small mistakes.",
     "It fixes things just long enough to blame you later."},
    {"Mercy Bolt Cutter", "tool", Slot::Tool, ItemImageKind::PrybarKit, 2, 1, 0, -1, 0, 0, 14, 206, 172, 106, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The padded handles settle in your palms like a late decision."},
     "Bolt cutters with padded handles and names scratched along both jaws.",
     "Every cut sounds like a decision being made too late."},
    {"Pulse Stapler", "tool", Slot::Tool, ItemImageKind::PrybarKit, 1, 2, 0, 0, 0, 1, 15, 208, 92, 112, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The stapler chirps through wire, cloth, and thin metal."},
     "A medical stapler rebuilt to bite wire, cloth, and thin metal.",
     "It closes wounds and opens questions."},
    {"Signal Chalk", "tool", Slot::Tool, ItemImageKind::SolderRig, 0, 2, 1, 1, 0, 0, 12, 82, 142, 234, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The chalk squeals before it agrees to write anything true."},
     "A stick of blue chalk used by antenna pilgrims to mark safe frequencies on concrete.",
     "The chalk squeals when it writes the truth."},
    {"Valve Rosary", "tool", Slot::Tool, ItemImageKind::PrybarKit, 1, 2, 0, 0, 1, 0, 16, 198, 150, 76, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Tiny brass valve wheels click through your fingers in order."},
     "A chain of tiny brass valve wheels threaded like prayer beads.",
     "It prays by opening pressure slowly."},
    {"Map Scalpel", "tool", Slot::Tool, ItemImageKind::SolderRig, 0, 2, 2, 1, 0, 1, 22, 226, 226, 178, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The blade touches the map and the city flinches."},
     "A thin ceramic blade used to cut old survey maps without tearing the paper.",
     "It cuts distance, but the city feels it."},
    {"Flare Hook", "weapon", Slot::Weapon, ItemImageKind::RailPistol, 2, 0, 0, 0, 0, 0, 13, 238, 82, 42, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The rescue flare hangs from the hook, waiting to become an argument."},
     "An emergency flare welded to a climbing hook and wrapped in old rescue tape.",
     "It is a rescue tool until pointed at someone."},
    {"Static Knife", "weapon", Slot::Weapon, ItemImageKind::QuietNailgun, 0, 2, 0, 2, 0, 1, 17, 142, 228, 218, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The antenna wire buzzes when conversation turns false."},
     "A short blade wrapped in antenna wire. It buzzes when conversation turns false.",
     "It cuts conversation before it cuts skin."},
    {"Toll Hammer", "weapon", Slot::Weapon, ItemImageKind::RailPistol, 3, 0, 0, -2, 0, 0, 16, 190, 116, 62, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The hammer weighs tolls, teeth, and locked things equally."},
     "A compact sledge marked with highway toll numbers and dried red paint.",
     "Every locked thing owes somebody money."},
    {"Mercy Siren", "weapon", Slot::Weapon, ItemImageKind::QuietNailgun, 0, 1, 1, 2, 0, 1, 18, 236, 110, 154, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The alarm does not scare people. It reminds them to leave."},
     "A handheld acoustic alarm tuned to make people step away without knowing why.",
     "It does not scare people. It reminds them to leave."},
    {"Rivet Saint", "weapon", Slot::Weapon, ItemImageKind::RailPistol, 3, 1, 0, -1, 0, 1, 20, 192, 94, 56, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The riveter kneels on its hose and fastens faith to metal."},
     "A pneumatic riveter with a copper figurine bolted to the side.",
     "It fastens faith to metal at unsafe speeds."},
    {"Cold Lantern", "weapon", Slot::Weapon, ItemImageKind::MourningLens, 1, 0, 2, 1, 1, 2, 24, 78, 166, 236, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Blue light fills the room the world was trying to hide."},
     "A lantern that burns blue without heat and makes shadows look guilty.",
     "It lights the room the world is trying to hide."},
    {"Civic Baton", "weapon", Slot::Weapon, ItemImageKind::QuietNailgun, 2, 1, 0, -1, 0, 0, 12, 92, 104, 128, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "It feels official in the hand and dirty everywhere else."},
     "A collapsible baton stamped PROPERTY OF MUNICIPAL ORDER.",
     "It feels official in the hand and dirty everywhere else."},
    {"White Receipt", "artifact", Slot::Artifact, ItemImageKind::WarmBattery, 0, 2, 2, 0, 0, 2, 32, 238, 238, 220, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The receipt prints tomorrow's ink across your palm."},
     "A receipt for something the player has not bought yet. The total changes when observed.",
     "The ink is still wet with tomorrow."},
    {"The Spare Hour", "artifact", Slot::Artifact, ItemImageKind::WarmBattery, 0, 1, 1, 0, 0, 3, 40, 220, 180, 88, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The handless watch sweats and the day grows an extra tooth."},
     "A watch with no hands and a second crown that sweats in daylight.",
     "It gives you time from someone who still needs it."},
    {"Little Flood Saint", "artifact", Slot::Artifact, ItemImageKind::CopperSaint, 0, 0, 1, 0, 2, 1, 28, 82, 154, 206, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Coins shift under the figurine's tongue when the drains answer."},
     "A waterlogged figurine with coins tucked under its tongue.",
     "It prays in the currency of drains."},
    {"Apology Engine", "artifact", Slot::Artifact, ItemImageKind::NullCharm, 0, 2, 0, 1, 0, 2, 31, 174, 154, 210, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The cube whispers sorry before it knows what you did."},
     "A metal cube that whispers apologies in voices you almost trust.",
     "It is sorry before it knows what you did."},
    {"Empty Name Tag", "artifact", Slot::Artifact, ItemImageKind::NullCharm, 0, 2, 0, 2, 0, 1, 27, 202, 218, 230, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The blank badge grants the confidence of someone underpaid and authorized."},
     "A plastic employee badge with no name, no photo, and perfect access wear.",
     "It grants the confidence of someone underpaid and authorized."},
    {"Black Reed Seed", "artifact", Slot::Artifact, ItemImageKind::NullCharm, 0, 0, 2, 1, 1, 2, 29, 54, 124, 86, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The seed clicks against glass and changes pockets when ignored."},
     "A hard seed that clicks against glass and never appears in the same pocket twice.",
     "It wants to be planted in a road."},
    {"Borrowed Shadow", "artifact", Slot::Artifact, ItemImageKind::NullCharm, 0, 0, 0, 3, 0, 2, 35, 52, 58, 78, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "A folded square of darkness stands where you should have been seen."},
     "A folded square of darkness pinned with a silver office clip.",
     "It stands where you should have been seen."},
    {"Copper Tooth Radio", "artifact", Slot::Artifact, ItemImageKind::WarmBattery, 0, 2, 2, 0, 0, 2, 34, 196, 118, 62, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Chewing static gathers in the little copper tooth."},
     "A tiny radio built into a human-sized copper tooth.",
     "It receives the bite marks of old broadcasts."},
    {"Mercy Bell", "artifact", Slot::Artifact, ItemImageKind::CopperSaint, 1, 0, 0, 0, 1, 2, 33, 218, 188, 126, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The cracked bell rings only when nobody moves."},
     "A cracked handbell with no clapper. It rings only when nobody moves.",
     "It calls a rescue that invoices later."},
    {"Calendar of Rains", "artifact", Slot::Artifact, ItemImageKind::MourningLens, 0, 1, 2, 0, 1, 1, 26, 104, 178, 226, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Every date says RAIN. Several are crossed out in blood."},
     "A pocket calendar where every date is marked RAIN.",
     "It knows the forecast because the forecast owes it money."},
    {"Redacted Photograph", "artifact", Slot::Artifact, ItemImageKind::MourningLens, 0, 0, 1, 2, 0, 2, 30, 164, 86, 96, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "Every blacked-out face tries not to recognize you."},
     "A family photograph where every face has been blacked out except yours.",
     "Everyone in the picture is trying not to recognize you."},
    {"The Tenth Button", "artifact", Slot::Artifact, ItemImageKind::WarmBattery, 0, 2, 1, 0, 1, 2, 36, 210, 180, 86, 0,
     {ItemUseKind::Equip, 0, 0, 0, false, "Equip", "The brass B10 button is warm from being pressed by people below."},
     "A brass elevator button labelled B10, though the Mall map ends at B3.",
     "It is warm from being pressed by people who did not come back up."},
    {"Ghost Tea Ampoule", "dose", Slot::Consumable, ItemImageKind::IodineAmpoule, 0, 0, 0, 0, 0, 0, 6, 184, 226, 198, 0,
     {ItemUseKind::Consume, 0, 0, 0, true, "Drink", "The pale tea makes the next site feel easier to disappear inside."},
     "A glass vial of pale tea brewed from greenhouse leaves and clinic alcohol.",
     "It tastes like hiding under a table as a child."},
    {"Black Iodine Strip", "dose", Slot::Consumable, ItemImageKind::IodineAmpoule, 0, 0, 0, 0, 0, 0, 7, 44, 42, 64, 0,
     {ItemUseKind::Consume, 0, -3, 0, true, "Use Strip", "The strip stains your tongue black and teaches panic to be useful."},
     "A dissolving black strip placed under the tongue before bad exposure work.",
     "It stains the tongue the colour of useful panic."},
    {"Sleepless Mint", "dose", Slot::Consumable, ItemImageKind::CannedCoffee, 0, 0, 0, 0, 0, 0, 5, 144, 226, 126, 0,
     {ItemUseKind::Consume, 0, 0, 0, true, "Chew", "The mint tastes green, sharp, and legally indefensible."},
     "A foil-wrapped stimulant sweet from a vending machine that should not work.",
     "It tastes green, sharp, and legally indefensible."},
    {"Fence Runner's Salt", "dose", Slot::Consumable, ItemImageKind::IodineAmpoule, 0, 0, 0, 0, 0, 0, 5, 188, 188, 176, 0,
     {ItemUseKind::Consume, 0, 0, 0, true, "Rub Salt", "Grey salt bites into your gloves. Your hands remember fences."},
     "A twist of grey salt rubbed into gloves before climbing watched routes.",
     "It makes your hands remember fences they never climbed."},
    {"Cheap Courage Syrup", "dose", Slot::Consumable, ItemImageKind::CannedCoffee, 0, 0, 0, 0, 0, 0, 5, 164, 94, 48, 0,
     {ItemUseKind::Consume, 0, 0, 0, true, "Drink", "Bad ideas stand up straighter in your blood."},
     "A brown clinic syrup with a label mostly made of warnings.",
     "It makes bad ideas stand up straight."},
    {"Blue Milk Sachet", "dose", Slot::Consumable, ItemImageKind::CannedCoffee, 0, 0, 0, 0, 0, 0, 6, 116, 176, 236, 0,
     {ItemUseKind::Consume, 1, -1, 0, true, "Drink", "The world becomes mercifully blurry. Your hands stop buzzing."},
     "A single-use ration of mineral milk issued to cleanup crews before the colour blue was recalled.",
     "It tastes like childhood, chalk, and corporate liability."},
};

const uint8_t kItemCount = sizeof(itemCatalog) / sizeof(itemCatalog[0]);

// Site text gives the world sensory anchors: ground, weather, smell, sound, and
// the people who survive by reading small changes in the Zone.
Site sites[] = {
    {"Underpass Clinic", "safe berth",
     "A medic shack below the ring road, where runoff clicks through drain grates and warm bulbs turn the damp concrete amber. It smells of bad coffee, antiseptic, diesel coats, and fear kept politely quiet; orderlies, fence-runners, and debt collectors all lower their voices near the triage curtain.",
     "From the clinic steps you watch the waiting line shift whenever the road lights flicker; people hide tremors in their coat pockets, and the orderlies read every cough like weather.",
     1, 0, 0},
    {"Neon Spillway", "wet market",
     "Old ad towers bleed color through toxic rain and illegal stalls crowd the flood channel. Fry oil, wet plastic, ozone, and incense hang under the tarps while smugglers haggle with scavengers, courier kids, and checkpoint guards pretending not to shop.",
     "You count patrol reflections in the spillway water, note which vendors stop talking first, and spot a courier marking safe stalls with chalk dust under the table lips.",
     3, 4, 0},
    {"Sunken Mall", "retail tomb",
     "Escalators vanish into black water and the public address system still whispers discounts to empty atriums. The air tastes of algae, copper wiring, perfume samples, and drowned plaster; families in patched waders sift storefronts while something below keeps the music playing.",
     "You hold still above the atrium and listen: water slaps tile, a child laughs once behind a shutter, and the old shop speakers skip whenever something moves below.",
     4, 5, 0},
    {"Relay Grave", "antenna field",
     "Fallen towers tick in the wind across a hill of cable bones and shattered insulators. Messages still arrive for the dead, buzzing from rusted cabinets that smell of hot dust and mouse nests, and the antenna pilgrims trade batteries for frequencies they swear contain names.",
     "You watch the tower shadows crawl the wrong direction and mark which cabinets click in answer; an antenna pilgrim leaves offerings where the static briefly sounds human.",
     5, 4, 0},
    {"Black Reed Verge", "outer exclusion",
     "A reed sea has grown through the asphalt until the road looks woven from knives. Sweet chemical rot rises from the ditches, insects rasp inside the fog, and quiet homesteads on scaffold legs watch the stalks for the moment every shadow leans the wrong way.",
     "You crouch in the ditch grass and let the reedline teach you its rhythm; hidden homes go dark in sequence, then one patch of stalks keeps moving after the wind stops.",
     6, 3, 0},
};

const uint8_t kSiteCount = sizeof(sites) / sizeof(sites[0]);

// Map pins read like field annotations rather than neutral labels.
MapPin mapPins[] = {
    {0, 150, 700, "CLINIC", "Blue ward light, wet concrete, and a queue of people counting pills in their palms."},
    {1, 320, 510, "SPILL", "Ad ghosts stutter: BUY CLEAN WATER / BUY CLEAN SKIN, while vendors laugh under leaking tarps."},
    {2, 510, 670, "MALL", "Retail hymns leak from drowned escalators after dusk. Boots splash where music should end."},
    {3, 660, 360, "RELAY", "Antenna shadows point against the wind. The cabinets answer voices nobody transmitted."},
    {4, 850, 190, "VERGE", "The reedline redraws itself between blinks. Smoke from hidden homes smells sweet and wrong."},
};

const uint8_t kMapPinCount = sizeof(mapPins) / sizeof(mapPins[0]);

// Route edges are named so travel text can refer to lived-in paths.
RouteEdge routeEdges[] = {
    {0, 1, "drain road"},
    {0, 2, "service tunnel"},
    {1, 2, "flood arcade"},
    {1, 3, "signage spine"},
    {2, 3, "maintenance tram"},
    {2, 4, "reed culvert"},
    {3, 4, "antenna ridge"},
};

const uint8_t kRouteEdgeCount = sizeof(routeEdges) / sizeof(routeEdges[0]);
